include:
  - path: ./backend/docker-compose.yml
    env_file:
      - ./backend/.env.docker
      - ./backend/.env.local
  
  - path: ./frontend/docker-compose.yml

networks:
  creditall_dev_network:
    name: creditall_dev_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
